DROP TABLE IF EXISTS cart CASCADE;

CREATE TABLE cart (
    id SERIAL PRIMARY KEY,
    session_id INT NOT NULL,
    product_id INTEGER REFERENCES products(id),
    quantity INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);